version: '3.5'

services:
  third-party:
    build:
      context: ./third-party
      dockerfile: Dockerfile
    container_name: third-party
    restart: always
    ports:
      - '3003:3003'
    networks:
      - internal_network
    volumes:
      - ./third-party/src:/app/src
      
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: back-end
    restart: always
    depends_on:
      - third-party
    ports:
      - '3004:3004'
    networks:
      - internal_network
    volumes:
      - ./back-end/src:/app/src

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: front-end
    ports:
      - '3001:3001'
    networks:
      - internal_network
    depends_on:
      - back-end
    volumes:
      - ./front-end/src:/app/src

networks:
  internal_network:

volumes:
  mongo_data: